module ImmGen(
  input  [11:0] io_iImm, // @[src/main/scala/idu/ImmGen.scala 7:20]
  input  [11:0] io_sImm, // @[src/main/scala/idu/ImmGen.scala 7:20]
  input  [12:0] io_bImm, // @[src/main/scala/idu/ImmGen.scala 7:20]
  input  [31:0] io_uImm, // @[src/main/scala/idu/ImmGen.scala 7:20]
  input  [20:0] io_jImm, // @[src/main/scala/idu/ImmGen.scala 7:20]
  input  [2:0]  io_immType, // @[src/main/scala/idu/ImmGen.scala 7:20]
  output [31:0] io_imm // @[src/main/scala/idu/ImmGen.scala 7:20]
);
  wire [19:0] _iImmWire_T_1 = io_iImm[11] ? 20'hfffff : 20'h0; // @[src/main/scala/idu/ImmGen.scala 18:35]
  wire [31:0] iImmWire = {_iImmWire_T_1,io_iImm}; // @[src/main/scala/idu/ImmGen.scala 18:30]
  wire [19:0] _sImmWire_T_1 = io_sImm[11] ? 20'hfffff : 20'h0; // @[src/main/scala/idu/ImmGen.scala 19:35]
  wire [31:0] sImmWire = {_sImmWire_T_1,io_sImm}; // @[src/main/scala/idu/ImmGen.scala 19:30]
  wire [18:0] _bImmWire_T_1 = io_bImm[12] ? 19'h7ffff : 19'h0; // @[src/main/scala/idu/ImmGen.scala 20:35]
  wire [31:0] bImmWire = {_bImmWire_T_1,io_bImm}; // @[src/main/scala/idu/ImmGen.scala 20:30]
  wire [10:0] _jImmWire_T_1 = io_jImm[20] ? 11'h7ff : 11'h0; // @[src/main/scala/idu/ImmGen.scala 22:35]
  wire [31:0] jImmWire = {_jImmWire_T_1,io_jImm}; // @[src/main/scala/idu/ImmGen.scala 22:30]
  wire  _io_imm_T = io_immType == 3'h1; // @[src/main/scala/idu/ImmGen.scala 26:70]
  wire  _io_imm_T_1 = io_immType == 3'h2; // @[src/main/scala/idu/ImmGen.scala 27:78]
  wire  _io_imm_T_2 = io_immType == 3'h3; // @[src/main/scala/idu/ImmGen.scala 28:78]
  wire  _io_imm_T_3 = io_immType == 3'h4; // @[src/main/scala/idu/ImmGen.scala 29:78]
  wire  _io_imm_T_4 = io_immType == 3'h5; // @[src/main/scala/idu/ImmGen.scala 30:78]
  wire [31:0] _io_imm_T_5 = _io_imm_T_4 ? jImmWire : 32'h0; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire [31:0] _io_imm_T_6 = _io_imm_T_3 ? io_uImm : _io_imm_T_5; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire [31:0] _io_imm_T_7 = _io_imm_T_2 ? bImmWire : _io_imm_T_6; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire [31:0] _io_imm_T_8 = _io_imm_T_1 ? sImmWire : _io_imm_T_7; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  assign io_imm = _io_imm_T ? iImmWire : _io_imm_T_8; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
endmodule
