module AXISkidBuffer(
  input         io_axiMaster_arready, // @[src/main/scala/basemode/Memory.scala 651:16]
  output        io_axiMaster_arvalid, // @[src/main/scala/basemode/Memory.scala 651:16]
  output [31:0] io_axiMaster_araddr, // @[src/main/scala/basemode/Memory.scala 651:16]
  output [7:0]  io_axiMaster_arlen, // @[src/main/scala/basemode/Memory.scala 651:16]
  output        io_axiMaster_rready, // @[src/main/scala/basemode/Memory.scala 651:16]
  input         io_axiMaster_rvalid, // @[src/main/scala/basemode/Memory.scala 651:16]
  input  [31:0] io_axiMaster_rdata, // @[src/main/scala/basemode/Memory.scala 651:16]
  input         io_axiMaster_rlast, // @[src/main/scala/basemode/Memory.scala 651:16]
  output        io_axiSlave_arready, // @[src/main/scala/basemode/Memory.scala 651:16]
  input         io_axiSlave_arvalid, // @[src/main/scala/basemode/Memory.scala 651:16]
  input  [31:0] io_axiSlave_araddr, // @[src/main/scala/basemode/Memory.scala 651:16]
  input  [7:0]  io_axiSlave_arlen, // @[src/main/scala/basemode/Memory.scala 651:16]
  input         io_axiSlave_rready, // @[src/main/scala/basemode/Memory.scala 651:16]
  output        io_axiSlave_rvalid, // @[src/main/scala/basemode/Memory.scala 651:16]
  output [31:0] io_axiSlave_rdata, // @[src/main/scala/basemode/Memory.scala 651:16]
  output        io_axiSlave_rlast // @[src/main/scala/basemode/Memory.scala 651:16]
);
  assign io_axiMaster_arvalid = io_axiSlave_arvalid; // @[src/main/scala/basemode/Memory.scala 748:37]
  assign io_axiMaster_araddr = io_axiSlave_araddr; // @[src/main/scala/basemode/Memory.scala 749:37]
  assign io_axiMaster_arlen = io_axiSlave_arlen; // @[src/main/scala/basemode/Memory.scala 751:37]
  assign io_axiMaster_rready = io_axiSlave_rready; // @[src/main/scala/basemode/Memory.scala 774:37]
  assign io_axiSlave_arready = io_axiMaster_arready; // @[src/main/scala/basemode/Memory.scala 747:37]
  assign io_axiSlave_rvalid = io_axiMaster_rvalid; // @[src/main/scala/basemode/Memory.scala 775:37]
  assign io_axiSlave_rdata = io_axiMaster_rdata; // @[src/main/scala/basemode/Memory.scala 777:37]
  assign io_axiSlave_rlast = io_axiMaster_rlast; // @[src/main/scala/basemode/Memory.scala 778:37]
endmodule
