module BranchCond(
  input  [3:0] io_branch, // @[src/main/scala/lsu/LSU.scala 340:20]
  input        io_less, // @[src/main/scala/lsu/LSU.scala 340:20]
  input        io_zero, // @[src/main/scala/lsu/LSU.scala 340:20]
  output [1:0] io_pcASrc, // @[src/main/scala/lsu/LSU.scala 340:20]
  output [1:0] io_pcBSrc // @[src/main/scala/lsu/LSU.scala 340:20]
);
  wire  _io_pcASrc_T = io_branch == 4'h0; // @[src/main/scala/lsu/LSU.scala 356:29]
  wire  _io_pcASrc_T_1 = io_branch == 4'h1; // @[src/main/scala/lsu/LSU.scala 357:29]
  wire  _io_pcASrc_T_2 = io_branch == 4'h2; // @[src/main/scala/lsu/LSU.scala 358:29]
  wire  _io_pcASrc_T_3 = io_branch == 4'h4; // @[src/main/scala/lsu/LSU.scala 359:29]
  wire  _io_pcASrc_T_4 = io_branch == 4'h5; // @[src/main/scala/lsu/LSU.scala 360:29]
  wire  _io_pcASrc_T_5 = ~io_zero; // @[src/main/scala/lsu/LSU.scala 360:48]
  wire  _io_pcASrc_T_6 = io_branch == 4'h6; // @[src/main/scala/lsu/LSU.scala 361:29]
  wire  _io_pcASrc_T_7 = io_branch == 4'h7; // @[src/main/scala/lsu/LSU.scala 362:29]
  wire  _io_pcASrc_T_8 = ~io_less; // @[src/main/scala/lsu/LSU.scala 362:48]
  wire  _io_pcASrc_T_9 = io_branch == 4'h8; // @[src/main/scala/lsu/LSU.scala 363:29]
  wire [1:0] _io_pcASrc_T_10 = _io_pcASrc_T_9 ? 2'h2 : 2'h0; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire [1:0] _io_pcASrc_T_11 = _io_pcASrc_T_7 ? {{1'd0}, _io_pcASrc_T_8} : _io_pcASrc_T_10; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire [1:0] _io_pcASrc_T_12 = _io_pcASrc_T_6 ? {{1'd0}, io_less} : _io_pcASrc_T_11; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire [1:0] _io_pcASrc_T_13 = _io_pcASrc_T_4 ? {{1'd0}, _io_pcASrc_T_5} : _io_pcASrc_T_12; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire [1:0] _io_pcASrc_T_14 = _io_pcASrc_T_3 ? {{1'd0}, io_zero} : _io_pcASrc_T_13; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire [1:0] _io_pcASrc_T_15 = _io_pcASrc_T_2 ? 2'h1 : _io_pcASrc_T_14; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire [1:0] _io_pcASrc_T_16 = _io_pcASrc_T_1 ? 2'h1 : _io_pcASrc_T_15; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  assign io_pcASrc = _io_pcASrc_T ? 2'h0 : _io_pcASrc_T_16; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  assign io_pcBSrc = _io_pcASrc_T_9 ? 2'h2 : {{1'd0}, _io_pcASrc_T_2}; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
endmodule
